receptionist/config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :patients
  get 'line_admin/index'
  get 'line_admin/createappointment'

  post 'line_admin/sort'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

receptionist/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

receptionist/app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :patient

  enum appointmentstatus: [ :newappointment, :inwaitingroom, :intreatment, :done ]
  enum classification: [ :covid19, :covid19suspect, :riskoflife, :standard ]

  def estimatedWaitingTime
    appointments = Appointment.where(datetime: self.datetime.all_day).where(sortOrder: 0..self.sortOrder).where.not(appointmentstatus: :done).order(:sortOrder)
    waitingTime = 0
    appointments.each { |a| waitingTime+=a.estimatedTimeForTreatment }

    return waitingTime
  end

  # Calculates the estimated time for this treatment
  def estimatedTimeForTreatment
    if self.covid19?
      return 10
    elsif self.standard?
      return 10
    elsif self.covid19suspect?
      return 30
    elsif self.riskoflife?
      return 10
    else
      # any unknown classification?
      return 45
    end
  end


  def as_json(options = { })
    super((options || { }).merge({
      :methods => [:estimatedWaitingTime]
    }))
  end
end

receptionist/app/models/patient.rb
class Patient < ApplicationRecord
    has_many :appointments
end

receptionist/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

receptionist/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @patient_id = params[:patient_id]
    @appointment = Appointment.new
    @appointment.patient = Patient.find(@patient_id)
    puts @appointment.inspect
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)
    puts @appointment.inspect
    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:datetime, :status, :classification, :remarks, :sortOrder, :patient_id)
    end
end

receptionist/app/controllers/line_admin_controller.rb
class LineAdminController < ApplicationController

  def index
    date = params["date"]
    puts date

    if date.present?
      dt = DateTime.strptime(date, "%Y%m%d")
    else
      dt = DateTime.current()
    end

    if dt.today?
      @date = 'Heute, ' + dt.to_s(:ger_format)
    else
      @date = I18n.l(dt, format: :ger_with_weekday, locale: "de")
    end

    @nextday = dt.next_day.to_s(:year_month_day)
    @previousday = dt.prev_day.to_s(:year_month_day)
    # to be done: check if free appointments are available for today.
    @freeAppointmentsAvailable = true

    @appointmentsScheduled = Appointment.where(datetime: dt.all_day).where.not(appointmentstatus: :done).order(:sortOrder)
    
    # only if there are no free appointments search for appointments to be triaged.
    # otherwise just use an empty list
    if @freeAppointmentsAvailable
      @appointmentsWaitingList = []
    else 
      @appointmentsWaitingList = Appointment.where(datetime: dt.all_day).where.not(appointmentstatus: :done).where(appointmentstatus: :newappointment).order(:sortOrder)
    end
  end

  # Apply a new sort to our entries in our frontend
  def sort
    newOrderedList = params[:list].split(",").map(&:to_i)
    puts "clients new order is: " + newOrderedList.to_s
    # get all appointments for this day
    appointments = Appointment.where(id: newOrderedList)

    # and recalculate the order
    for appointment in appointments do
      appointment.sortOrder = newOrderedList.index(appointment.id)
      appointment.save
    end
    render json: appointments.sort_by(&:sortOrder)
  end

  # Create a new appointment
  def createappointment
    puts "Create appointment called"
    @appointment = Appointment.new
  end
end

receptionist/app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to controller: :appointments, action: :new, patient_id: @patient.id }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:birthday, :name, :timeToDoc, :phone, :email)
    end
end

receptionist/app/controllers/questionnaire_controller.rb
class QuestionnaireController < ApplicationController
  def intro

  end
  def questions

  end
end

receptionist/app/helpers/application_helper.rb
module ApplicationHelper
end

receptionist/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

receptionist/app/helpers/line_admin_helper.rb
module LineAdminHelper
end

receptionist/app/helpers/patients_helper.rb
module PatientsHelper
end

receptionist/app/helpers/questionnaire_helper.rb
module QuestionnaireHelper
end

receptionist/app/views/appointments/_form.html.erb
<h1><%= @appointment.patient.name %></h1>
<%= form_with(model: appointment, local: true) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :datetime %>
    <%= form.datetime_select :datetime %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :classification %>
    <%= form.text_field :classification %>
  </div>

  <div class="field">
    <%= form.label :remarks %>
    <%= form.text_area :remarks %>
  </div>

  <div class="field">
    <%= form.label :sortOrder %>
    <%= form.number_field :sortOrder %>
  </div>

  <div class="field" style="display:none;">
    <%= form.label :patient_id %>
    <%= form.text_field :patient_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

receptionist/app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

receptionist/app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Datetime</th>
      <th>Status</th>
      <th>Classification</th>
      <th>Remarks</th>
      <th>Sortorder</th>
      <th>Patient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.datetime %></td>
        <td><%= appointment.appointmentstatus %></td>
        <td><%= appointment.classification %></td>
        <td><%= appointment.remarks %></td>
        <td><%= appointment.sortOrder %></td>
        <td><%= appointment.patient_id %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

receptionist/app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment, patientid: @patient_id  %>

<%= link_to 'Back', appointments_path %>

receptionist/app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Datetime:</strong>
  <%= @appointment.datetime %>
</p>

<p>
  <strong>Status:</strong>
  <%= @appointment.appointmentstatus %>
</p>

<p>
  <strong>Classification:</strong>
  <%= @appointment.classification %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @appointment.remarks %>
</p>

<p>
  <strong>Sortorder:</strong>
  <%= @appointment.sortOrder %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @appointment.patient_id %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

receptionist/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Receptionist</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="wrapper">
  <%= yield %>
</div>
</body>
</html>

receptionist/app/views/line_admin/index.html.erb
<div class="row">
  <div class="column-6">
    <h1>Termine</h1>
  </div>
  <div class="column-6">
    <div class="row">
      <div class="column-8">
        <p class="float-right" style="font-size:24pt;"><%= @date %></p>
      </div>
      <div class="column-2">
        <div class="btn-group float-right">
          <%= link_to '<button class="btn btn-icon"><i class="material-icons">chevron_left</i></button>'.html_safe, {date: @previousday} %>
          <%= link_to '<button class="btn btn-icon"><i class="material-icons">chevron_right</i></button>'.html_safe, {date: @nextday} %>
        </div>
      </div>
      <div class="column-1">
        <%= link_to '<button class="btn btn-icon"><i class="material-icons">add</i></button>'.html_safe, "/patients/new" %>
      </div>
    </div>
  </div>
</div>

<table>
  <thead>
  <tr>
    <th>Status</th>
    <th>Wunschtermin</th>
    <th>Patient</th>
    <th>Klassifikation</th>
    <th>Notiz</th>
    <th>Aktuelle Wartedauer</th>
    <th>Aktionen</th>
  </tr>
  </thead>
  <tbody class="sortable">
  <% @appointmentsScheduled.each do |appointment| %>
    <tr id="<%= appointment.id %>">
      <td><%= appointment.appointmentstatus %> </td>
      <td><%= appointment.datetime.strftime("%H:%M") %> </td>
      <td><%= appointment.patient.name %> </td>
      <td><%= appointment.classification %> </td>
      <td><%= appointment.remarks %> </td>
      <td><%= appointment.estimatedWaitingTime %> </td>
      <td></td>
    </tr>

  <% end %>

  </tbody>
</table>

<h1>Angefragte Termine (Warteliste)</h1>


<% if @freeAppointmentsAvailable %>
  <span>Gibt noch genug freie Slots heute</span>
<% else %>
  <table>
    <thead>
    <tr>
      <th>Status</th>
      <th>Wunschtermin</th>
      <th>Patient</th>
      <th>Klassifikation</th>
      <th>Notiz</th>
      <th>Aktionen</th>
    </tr>
    </thead>
    <tbody>
    <% @appointmentsWaitingList.each do |appointment| %>
      <tr>
        <td><%= appointment.appointmentstatus %> </td>
        <td><%= appointment.datetime.strftime("%H:%M") %> </td>
        <td><%= appointment.patient.name %> </td>
        <td><%= appointment.classification %> </td>
        <td><%= appointment.remarks %> </td>
        <td></td>
      </tr>

    <% end %>

    </tbody>
  </table>
<% end %>

<%= javascript_pack_tag 'line_admin' %>

receptionist/app/views/patients/_form.html.erb
<%= form_with(model: patient, local: true) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :birthday %>
    <%= form.date_select :birthday %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :timeToDoc %>
    <%= form.number_field :timeToDoc %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

receptionist/app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

receptionist/app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Patients</h1>

<table>
  <thead>
    <tr>
      <th>Birthday</th>
      <th>Name</th>
      <th>Timetodoc</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.birthday %></td>
        <td><%= patient.name %></td>
        <td><%= patient.timeToDoc %></td>
        <td><%= patient.phone %></td>
        <td><%= patient.email %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

receptionist/app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Back', patients_path %>

receptionist/app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Birthday:</strong>
  <%= @patient.birthday %>
</p>

<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<p>
  <strong>Timetodoc:</strong>
  <%= @patient.timeToDoc %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @patient.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @patient.email %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>

receptionist/app/views/questionnaire/intro.html.erb
<div>
  <div class="column-12">
    <%= render :partial => 'shared/header' %>
  </div>
  <div class="column-10">
    <div class='questionaire-intro-container'>
      <h1>Digitale Terminanfrage</h1>
      <div class="questionaire-intro-message-container column-12">
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.</p>
        <br>
        <br>
        <strong>***Erklärung****</strong>
      </div>
      <div class="column-3"></div>
      <div class="column-6 questionaire-intro-btn-container">
        <%= button_to "Terminanfrage starten", questionnaire_questions_path() , :method => "get", class: "btn" %>
      </div>
    </div>
  </div>
  <div class="column-2">
    <%= render :partial => 'shared/aside' %>
  </div>
</div>

receptionist/app/views/questionnaire/questions.html.erb
<div>
  <div class="column-12">
    <%= render :partial => 'shared/header' %>
  </div>
  <div class="column-10">
    <div class='questionaire-intro-container'>
      
    </div>
  </div>
  <div class="column-2">
    <%= render :partial => 'shared/aside' %>
  </div>
  <div class="column-12">
    <div class="questionaire-question-footer">
      <div></div>
      <div class="btn-group float-right">
          <button class="btn btn-default"><</button>
          <button class="btn btn-default">></button>
      </div>
    </div>
  </div>
</div>

receptionist/app/views/shared/_aside.html.erb
<aside>
  <h3>Terminanfrage</h3>
  <br>
  <span>Praxis</span><br>
  <span>Dr. Babel</span><br>
  <span>Elfenweg 42</span><br>
  <span>1337 Bothave</span><br>
</aside>

receptionist/app/views/shared/_header.html.erb
<Header>
  <span>Smarte Warte</span>
</Header>